language: java

after_success:
- mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report

notifications:
  slack:
    secure: yoEiartTToGgIIkxbtvQHsPYXjZK0CPDsNN3KJ6ZHuObdt0KbEihrhR3DWikWn3B+oCW5HQpVZoU8GtYxS5PlJguXLbEO44sqWXaCktEM4vvJILDsjLc6WkL1lkDXZU2z/F9y81f7l9NTmDkIxcRgsDUBmGz59alDw3mq1VGEL7Gq3LjP7PhgdmECN42I4lBE4S6H5a6sJNAr1PQ4zc2/xntu529mesn7VKDTF5FLm/ubSFlOBtKrIMBIxG7w9SYVZBwlX5EGtgSj4yojbWjPkhtPjyBcuzCv6tTus1Z21iDt2Iu9NK4fZPqZPE8tNPZuliwoFBfU/Dq9tP/qP9WRvxztX71vSucFbVm672nrdxeepgWK6+6RI7+wgKOZyAa8awNrv4hZUvicKO9tJwHzh/GbavaQ6+keLfkOifmO4Jh7d02zVQCswb+DuPbcV4U/FPTm5CK8bWx+eVrNN0oGTBkkp2b2mudDEgi/7TUOru/DD3P5mkosigRSGCRRDdoXl4uvObKP9BvlsFOMg3pt3U8L6GduHKi7l0uv5bfIIbc61Nq97LH7eDXEufsSRa/fLFSARBguO+e/9/jd92CVNJkedGqkTLwU37cdThXkEOgOhDnMUcfV6CayV++BKpHoSvOdBEoOzyz5DY/DZNbODMkaMC3IlqNspWnJOPrYqE=
